### ISSUE TITLE
Code customizing issue

### ISSUE THREAD

**Issue by jusepv** [app-generator/django-dashboard-kit#1]
Thanks for sharing this great resource.
I tried to modify it to fit my data, but modifying the data doesn't change the graph.
How do I fix it?

**Comment by app-generator** [comment]
Hello @jusepv 

The browser might use the old JS file. Try this:

- restart the Django app
- hard refresh the browser [ Shift + F5 in Chrome ]

Let us know here or via Discord if works. 

https://appseed.us/support/

TY!
